// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartingPath() {
  return window['go']['main']['App']['GetStartingPath']();
}

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function LoadPinnedFolders() {
  return window['go']['main']['App']['LoadPinnedFolders']();
}

export function LoadYourComputer() {
  return window['go']['main']['App']['LoadYourComputer']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ReadPath(arg1) {
  return window['go']['main']['App']['ReadPath'](arg1);
}

export function RenderPreviews(arg1, arg2) {
  return window['go']['main']['App']['RenderPreviews'](arg1, arg2);
}
