// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetStartingPath():Promise<string>;

export function Greet():Promise<void>;

export function LoadPinnedFolders():Promise<Array<models.LeftBarElement>>;

export function LoadYourComputer():Promise<Array<models.LeftBarElement>>;

export function OpenFile(arg1:string):Promise<void>;

export function ReadPath(arg1:string):Promise<Array<models.SysFile>>;

export function RenderPreviews(arg1:Array<models.SysFile>):Promise<Array<models.SysFile>>;
